@startuml LocalServer

title LocalServer

enum RequestType {
    + None
    + Video
    + Thumbnail
}

interface IServer {
    + void Start();
    + void ShutDown();
}

interface IUrlHandler {
    + RequestType GetReqyestType(Uri request);
}

interface IVideoRequestHandler {
    + IAttemptResult Handle(Uri request,HttpListenerResponse res);
}

interface INotFoundRequestHandler {
    + IAttemptResult Handle(HttpListenerResponse res);
}

IServer *-- IUrlHandler
IServer *-- IVideoRequestHandler
IServer *-- INotFoundRequestHandler
IServer ..> RequestType
IUrlHandler ..> RequestType

@enduml