using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Niconicome.Models.Domain.Niconico;

namespace NiconicomeTest.Stabs.Models.Domain.Niconico.NicoHttpStabs
{
    class NicoHttpStab : INicoHttp
    {
        public NicoHttpStab(HttpContent getContent, HttpContent putContent)
        {
            this.getContent = getContent;
            this.putContent = putContent;
            this.NiconicoBaseUri = new Uri("https://nicovideo.jp");
            this.NiconicoLoginUri = new Uri("https://secure.nicovideo.jp/secure/login?site=niconico");
            this.NiconicoLogoutUri = new Uri("https://account.nicovideo.jp/logout");
        }

        private readonly HttpContent getContent;

        private readonly HttpContent putContent;

        public async Task<string> GetStringAsync(Uri uri)
        {
            return await this.getContent.ReadAsStringAsync();
        }

        public Task<HttpResponseMessage> GetAsync(Uri uri)
        {
            var msg = new HttpResponseMessage
            {
                StatusCode = HttpStatusCode.OK,
                ReasonPhrase = "Generated by stab",
                Content = this.getContent,
            };

            return Task.FromResult(msg);
        }

        public Task<HttpResponseMessage> PostAsync(Uri uri, HttpContent content)
        {

            var msg = new HttpResponseMessage
            {
                StatusCode = HttpStatusCode.OK,
                ReasonPhrase = "Generated by stab",
                Content = this.putContent,
            };

            return Task.FromResult(msg);
        }

        public Task<HttpResponseMessage> OptionAsync(Uri uri)
        {

            var msg = new HttpResponseMessage
            {
                StatusCode = HttpStatusCode.OK,
                ReasonPhrase = "Generated by stab",
                Content = new StringContent("HTTP OPTION Method")
            };

            return Task.FromResult(msg);
        }

        public Uri NiconicoLoginUri { get; init; }

        public Uri NiconicoBaseUri { get; init; }

        public Uri NiconicoLogoutUri { get; init; }
    }
}
