//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiconicomeTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiconicomeTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string API_Mylist_Get {
            get {
                return ResourceManager.GetString("API_Mylist_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;ping&quot;:{&quot;content&quot;:&quot;rs: 0&quot;}},{&quot;ping&quot;:{&quot;content&quot;:&quot;ps: 0&quot;}},{&quot;thread&quot;:{&quot;thread&quot;:&quot;1173108780&quot;,&quot;version&quot;:&quot;20090904&quot;,&quot;fork&quot;:0,&quot;language&quot;:0,&quot;user_id&quot;:&quot;12345678&quot;,&quot;with_global&quot;:1,&quot;scores&quot;:1,&quot;nicoru&quot;:3,&quot;userkey&quot;:&quot;1611473223.~1~Oh8RqyodqkNiDk4_UjGjjgI2GflBg2nmG7JugAjyopQ&quot;}},{&quot;ping&quot;:{&quot;content&quot;:&quot;pf: 0&quot;}},{&quot;ping&quot;:{&quot;content&quot;:&quot;ps: 1&quot;}},{&quot;thread_leaves&quot;:{&quot;thread&quot;:&quot;1173108780&quot;,&quot;fork&quot;:0,&quot;language&quot;:0,&quot;user_id&quot;:&quot;12345678&quot;,&quot;content&quot;:&quot;0 - 6:100,500,nicoru: 100&quot;,&quot;scores&quot;:1,&quot;nicoru&quot;:3,&quot;userkey&quot;:&quot;1611473223.~1~Oh8RqyodqkNiDk4_UjGj [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommentRequest_sm9 {
            get {
                return ResourceManager.GetString("CommentRequest_sm9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///&quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///
        ///
        ///
        ///
        ///&lt;html class=&quot;gecko &quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///  try {
        ///    window.NicoGoogleTagManagerDataLayer = [];
        ///
        ///    var data = {};
        ///
        ///        data.user = (function () {
        ///      var user = {};
        ///
        ///                  user.login_status = &apos;not_login&apos;;
        ///      
        ///      return user;
        ///      })();
        ///
        ///    data.content = (function () {
        ///      var content = {};
        ///      content.community_id = &apos;3760945 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Elfenlied_Channel {
            get {
                return ResourceManager.GetString("Elfenlied_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;      &lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;http://nmsg.nicovideo.jp/api/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://public.api.nicovideo. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Niconico_Kakushigoto {
            get {
                return ResourceManager.GetString("Niconico_Kakushigoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;http://nmsg.nicovideo.jp/api/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://public.api.nicovideo.jp/&quot;&gt;&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Niconico_Onmyoji {
            get {
                return ResourceManager.GetString("Niconico_Onmyoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Onmyoji_Thumb {
            get {
                object obj = ResourceManager.GetObject("Onmyoji_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;      &lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;http://nmsg.nicovideo.jp/api/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://public.api.nicovideo.jp/&quot; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sm9_page {
            get {
                return ResourceManager.GetString("sm9_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;meta&quot;:{&quot;status&quot;:200},&quot;data&quot;:{&quot;totalCount&quot;:19,&quot;items&quot;:[{&quot;type&quot;:&quot;user&quot;,&quot;isCommunityMemberOnly&quot;:false,&quot;id&quot;:&quot;sm18219289&quot;,&quot;title&quot;:&quot;【ギャラ子β版】ANOTHER:WORLD (アニメversion)【デモ曲】&quot;,&quot;registeredAt&quot;:&quot;2012-06-29T16:38:10+09:00&quot;,&quot;count&quot;:{&quot;view&quot;:44932,&quot;comment&quot;:394,&quot;mylist&quot;:384},&quot;thumbnail&quot;:{&quot;url&quot;:&quot;https://nicovideo.cdn.nimg.jp/thumbnails/18219289/18219289&quot;,&quot;middleUrl&quot;:null,&quot;largeUrl&quot;:&quot;https://nicovideo.cdn.nimg.jp/thumbnails/18219289/18219289.L&quot;,&quot;listingUrl&quot;:&quot;https://img.cdn.nimg.jp/s/nicovideo/thumbnails/18219289/18219289. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string User_Video_Response {
            get {
                return ResourceManager.GetString("User_Video_Response", resourceCulture);
            }
        }
    }
}
