//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiconicomeTest.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NiconicomeTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {&quot;meta&quot;:{&quot;status&quot;:200},&quot;data&quot;:{&quot;mylist&quot;:{&quot;id&quot;:67607290,&quot;name&quot;:&quot;東方&quot;,&quot;description&quot;:&quot;&quot;,&quot;defaultSortKey&quot;:&quot;addedAt&quot;,&quot;defaultSortOrder&quot;:&quot;desc&quot;,&quot;items&quot;:[{&quot;itemId&quot;:1287138662,&quot;watchId&quot;:&quot;sm12438432&quot;,&quot;description&quot;:&quot;&quot;,&quot;addedAt&quot;:&quot;2020-02-18T20:02:17+09:00&quot;,&quot;status&quot;:&quot;public&quot;,&quot;video&quot;:{&quot;type&quot;:&quot;essential&quot;,&quot;id&quot;:&quot;sm12438432&quot;,&quot;title&quot;:&quot;ナズがSpring of Dreams(春の湊に)を踊ってくれました【東方MMD】&quot;,&quot;registeredAt&quot;:&quot;2010-10-15T19:31:02+09:00&quot;,&quot;count&quot;:{&quot;view&quot;:1193334,&quot;comment&quot;:8989,&quot;mylist&quot;:20296,&quot;like&quot;:48},&quot;thumbnail&quot;:{&quot;url&quot;:&quot;https://nicovideo.cdn.n [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string API_Mylist_Get {
            get {
                return ResourceManager.GetString("API_Mylist_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///&quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///
        ///
        ///
        ///
        ///&lt;html class=&quot;gecko &quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///  try {
        ///    window.NicoGoogleTagManagerDataLayer = [];
        ///
        ///    var data = {};
        ///
        ///        data.user = (function () {
        ///      var user = {};
        ///
        ///                  user.user_id = parseInt(&apos;74537208&apos;, 10) || null;
        ///      user.login_status = &apos;login&apos;;
        ///      user.member_status = &apos;premium&apos;;
        ///      user.birthday = &apos;1990-03-01&apos;;
        ///             [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Channel_7 {
            get {
                return ResourceManager.GetString("Channel_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [{&quot;ping&quot;:{&quot;content&quot;:&quot;rs: 0&quot;}},{&quot;ping&quot;:{&quot;content&quot;:&quot;ps: 0&quot;}},{&quot;thread&quot;:{&quot;thread&quot;:&quot;1173108780&quot;,&quot;version&quot;:&quot;20090904&quot;,&quot;fork&quot;:0,&quot;language&quot;:0,&quot;user_id&quot;:&quot;12345678&quot;,&quot;with_global&quot;:1,&quot;scores&quot;:1,&quot;nicoru&quot;:3,&quot;userkey&quot;:&quot;1611473223.~1~Oh8RqyodqkNiDk4_UjGjjgI2GflBg2nmG7JugAjyopQ&quot;}},{&quot;ping&quot;:{&quot;content&quot;:&quot;pf: 0&quot;}},{&quot;ping&quot;:{&quot;content&quot;:&quot;ps: 1&quot;}},{&quot;thread_leaves&quot;:{&quot;thread&quot;:&quot;1173108780&quot;,&quot;fork&quot;:0,&quot;language&quot;:0,&quot;user_id&quot;:&quot;12345678&quot;,&quot;content&quot;:&quot;0 - 6:100,500,nicoru: 100&quot;,&quot;scores&quot;:1,&quot;nicoru&quot;:3,&quot;userkey&quot;:&quot;1611473223.~1~Oh8RqyodqkNiDk4_UjGj [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommentRequest_sm9 {
            get {
                return ResourceManager.GetString("CommentRequest_sm9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot;
        ///&quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
        ///
        ///
        ///
        ///
        ///&lt;html class=&quot;gecko &quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///  try {
        ///    window.NicoGoogleTagManagerDataLayer = [];
        ///
        ///    var data = {};
        ///
        ///        data.user = (function () {
        ///      var user = {};
        ///
        ///                  user.user_id = parseInt(&apos;74537208&apos;, 10) || null;
        ///      user.login_status = &apos;login&apos;;
        ///      user.member_status = &apos;premium&apos;;
        ///      user.birthday = &apos;1990-03-01&apos;;
        ///             [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Elfenlied_Channel {
            get {
                return ResourceManager.GetString("Elfenlied_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [
        ///  {
        ///    &quot;url&quot;: &quot;https://api.github.com/repos/Hayao-H/Niconicome/releases/45486422&quot;,
        ///    &quot;assets_url&quot;: &quot;https://api.github.com/repos/Hayao-H/Niconicome/releases/45486422/assets&quot;,
        ///    &quot;upload_url&quot;: &quot;https://uploads.github.com/repos/Hayao-H/Niconicome/releases/45486422/assets{?name,label}&quot;,
        ///    &quot;html_url&quot;: &quot;https://github.com/Hayao-H/Niconicome/releases/tag/v0.7.1&quot;,
        ///    &quot;id&quot;: 45486422,
        ///    &quot;author&quot;: {
        ///      &quot;login&quot;: &quot;github-actions[bot]&quot;,
        ///      &quot;id&quot;: 41898282,
        ///      &quot;node_id&quot;: &quot;MDM6Qm90NDE4OTgyODI= [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GithubReleases {
            get {
                return ResourceManager.GetString("GithubReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;div class=&quot;IchibaForWatch&quot;&gt;
        ///    &lt;div class=&quot;IchibaForWatch_Header&quot;&gt;
        ///        &lt;div class=&quot;IchibaForWatch_Title&quot;&gt;
        ///            &lt;span class=&quot;IchibaForWatch_Title_Body&quot;&gt;ニコニコ市場&lt;/span&gt;
        ///            &lt;a href=&quot;https://qa.nicovideo.jp/faq/show/758?site_domain=default&quot; class=&quot;IchibaForWatch_Title_Hint&quot;
        ///                title=&quot;ニコニコ市場とは？&quot; target=&quot;_blank&quot;&gt;&lt;svg width=&quot;10px&quot; height=&quot;10px&quot; viewBox=&quot;0 0 10 10&quot;
        ///                    xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///                    &lt;path
        ///             [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IchibaHtml {
            get {
                return ResourceManager.GetString("IchibaHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;main&quot;:&quot;&lt;div class=\&quot;IchibaForWatch\&quot;&gt;\r\n  &lt;div class=\&quot;IchibaForWatch_Header\&quot;&gt;\r\n    &lt;div class=\&quot;IchibaForWatch_Title\&quot;&gt;\r\n      &lt;span class=\&quot;IchibaForWatch_Title_Body\&quot;&gt;\u30cb\u30b3\u30cb\u30b3\u5e02\u5834&lt;\/span&gt;\r\n      &lt;a href=\&quot;https:\/\/qa.nicovideo.jp\/faq\/show\/758?site_domain=default\&quot; class=\&quot;IchibaForWatch_Title_Hint\&quot; title=\&quot;\u30cb\u30b3\u30cb\u30b3\u5e02\u5834\u3068\u306f\uff1f\&quot; target=\&quot;_blank\&quot;&gt;&lt;svg width=\&quot;10px\&quot; height=\&quot;10px\&quot; viewBox=\&quot;0 0 10 10\&quot; xmlns=\&quot;http:\/\/www.w3.org\/ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IchibaResponse {
            get {
                return ResourceManager.GetString("IchibaResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;      &lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;http://nmsg.nicovideo.jp/api/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://public.api.nicovideo. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Niconico_Kakushigoto {
            get {
                return ResourceManager.GetString("Niconico_Kakushigoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;      &lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;http://nmsg.nicovideo.jp/api/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://public.api.nicovideo. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Niconico_Onmyoji {
            get {
                return ResourceManager.GetString("Niconico_Onmyoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Onmyoji_Thumb {
            get {
                object obj = ResourceManager.GetObject("Onmyoji_Thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja-jp&quot;&gt;
        ///&lt;head&gt;
        ///      
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt;
        ///    &lt;meta name=&quot;copyright&quot; content=&quot;&amp;copy; DWANGO Co., Ltd.&quot;&gt;
        ///    &lt;link rel=&quot;shortcut icon&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/images/favicon/favicon.ico&quot;&gt;&lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/images/favicon/32.png&quot; sizes=&quot;32x32&quot;&gt;&lt;link rel=&quot;icon&quot; type=&quot;image/png&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/images/favicon/48.png&quot; si [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Series_Touhou {
            get {
                return ResourceManager.GetString("Series_Touhou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width,initial-scale=1.0&quot;&gt;      &lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://nicovideo.cdn.nimg.jp/web/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;http://nmsg.nicovideo.jp/api/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://ads.nicovideo.jp/&quot;&gt;&lt;link rel=&quot;preconnect&quot; href=&quot;https://public.api.nicovideo. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sm9_page {
            get {
                return ResourceManager.GetString("sm9_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;meta&quot;:{&quot;status&quot;:200},&quot;data&quot;:{&quot;totalCount&quot;:19,&quot;items&quot;:[{&quot;type&quot;:&quot;user&quot;,&quot;isCommunityMemberOnly&quot;:false,&quot;id&quot;:&quot;sm18219289&quot;,&quot;title&quot;:&quot;【ギャラ子β版】ANOTHER:WORLD (アニメversion)【デモ曲】&quot;,&quot;registeredAt&quot;:&quot;2012-06-29T16:38:10+09:00&quot;,&quot;count&quot;:{&quot;view&quot;:44932,&quot;comment&quot;:394,&quot;mylist&quot;:384},&quot;thumbnail&quot;:{&quot;url&quot;:&quot;https://nicovideo.cdn.nimg.jp/thumbnails/18219289/18219289&quot;,&quot;middleUrl&quot;:null,&quot;largeUrl&quot;:&quot;https://nicovideo.cdn.nimg.jp/thumbnails/18219289/18219289.L&quot;,&quot;listingUrl&quot;:&quot;https://img.cdn.nimg.jp/s/nicovideo/thumbnails/18219289/18219289. [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string User_Video_Response {
            get {
                return ResourceManager.GetString("User_Video_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {&quot;mainPage&quot;:{&quot;videoList&quot;:{&quot;videoListItemHeight&quot;:200}}} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string userChrome {
            get {
                return ResourceManager.GetString("userChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1	32		履歴
        ///2	0		最近再生した動画	&lt;最近再生した動画の一覧&gt;
        ///2	0		最近ダウンロードした動画	&lt;最近何かのDLを試みた一覧&gt;
        ///2	0		最近ダウンロードに失敗した動画	&lt;最近何かのDLに失敗した一覧&gt;
        ///1	32		アニメ
        ///2	32		新しいフォルダ
        ///3	32		新しいフォルダ
        ///4	0		東方	G:\[app]niconico\NicomentXenoglossia\down\東方.txt	G:\[app]niconico\NicomentXenoglossia\down
        ///2	96		エルフェンリート	https://ch.nicovideo.jp/elfenlied	list\アニメ\エルフェンリート
        ///3	10		新しいフォルダ
        ///2	0	s=7	かくしごと	https://ch.nicovideo.jp/kakushigoto-anime	list\アニメ\かくしごと
        ///2	0	s=7	かぐや様は告らせたい？ 天才たちの恋愛頭脳戦	https://ch.nicovideo.jp/kaguya_love_anime	list\アニメ\かぐや様は告らせたい？ 天才たちの恋愛頭脳 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Xeno_Playlist_File {
            get {
                return ResourceManager.GetString("Xeno_Playlist_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *			－	[sm30703222]【東方アレンジ】海の中の蛙、常識を知らず【ネイティブフェイス】		G:\[app]niconico\NicomentXenoglossia\list\東方（アレンジ）\	31	17-02-24	sm30703222	8378
        ///*			－	[nm3859127]【東方】明治十七年のネイティブ紅茶館【アレンジ】		G:\[app]niconico\NicomentXenoglossia\list\東方（アレンジ）\	6243	08-07-05	nm3859127	250748
        ///*			－	[sm31688857]【C92】上海レトロスカ (上海紅茶館)		G:\[app]niconico\NicomentXenoglossia\list\東方（アレンジ）\	22	17-08-04	sm31688857	5599
        ///*			－	[sm13136461]【東方PV】きっともうはたらかない【IOSYS】(高画質・高音質版)H264		G:\[app]niconico\NicomentXenoglossia\list\東方（アレンジ）\	2437	10-12-26	sm131364 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Xeno_Video_File {
            get {
                return ResourceManager.GetString("Xeno_Video_File", resourceCulture);
            }
        }
    }
}
