name: Test
on: [push]

jobs:

  publish:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
    - name:  Download ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        mkdir tmp -force
        mkdir ffmpeg/bin
        cd tmp
        Invoke-WebRequest https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-02-08-12-47/ffmpeg-n4.3.1-221-gd08bcbffff-win64-gpl-4.3.zip -o ffbin.zip
        Expand-Archive ffbin.zip -Force
        $item = Get-Childitem -Recurse -Filter ffmpeg.exe
        cd ..
        move $item[0].Fullname ./ffmpeg/bin
        echo $item[0].Fullname
        cd ffmpeg/bin
        ls
        cd ..
        cd ..
        del tmp -r
