name: ffmpeg
on: [push]

jobs:
  ffmpeg:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache ffmpeg
      id: cache-ffmpeg
      uses: actions/cache@v2
      env:
        cache-name: cache-ffmpeg
      with:
        path: ffmpeg
        key: ${{ runner.os }}-ffmpegbin
    - name:  Download ffmpeg
      if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        mkdir tmp -force
        mkdir ffmpeg/bin
        cd tmp
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2021-02-08-12-47/ffmpeg-n4.3.1-221-gd08bcbffff-win64-gpl-4.3.zip -o ffbin.zip
        Expand-Archive ffbin.zip -Force
        $item = Get-Childitem -Recurse -Filter ffmpeg.exe
        cd ..
        move $item[0].Fullname ./ffmpeg/bin
        del tmp -r
    - name: Check ffmpeg
      shell: powershell
      run: |
        cd ffmpeg/bin
        $files = ls -name
        echo $files
